In [114]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from scipy import stats 

In [115]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')

fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [116]:
fish

Species  Weight  Length  Diagonal   Height   Width
0     Bream   242.0    25.4      30.0  11.5200  4.0200
1     Bream   290.0    26.3      31.2  12.4800  4.3056
2     Bream   340.0    26.5      31.1  12.3778  4.6961
3     Bream   363.0    29.0      33.5  12.7300  4.4555
4     Bream   430.0    29.0      34.0  12.4440  5.1340
..      ...     ...     ...       ...      ...     ...
154   Smelt    12.2    12.2      13.4   2.0904  1.3936
155   Smelt    13.4    12.4      13.5   2.4300  1.2690
156   Smelt    12.2    13.0      13.8   2.2770  1.2558
157   Smelt    19.7    14.3      15.2   2.8728  2.0672
158   Smelt    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]

In [117]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(iris, test_size = 0.3)

train_set.shape
test_set.shape

NameError: name 'iris' is not defined

In [ ]:
fish.columns

In [118]:
fish.shape

(159, 6)

In [119]:
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [120]:
X=fish.drop('Species',axis=1)
X.head()

Weight  Length  Diagonal   Height   Width
0   242.0    25.4      30.0  11.5200  4.0200
1   290.0    26.3      31.2  12.4800  4.3056
2   340.0    26.5      31.1  12.3778  4.6961
3   363.0    29.0      33.5  12.7300  4.4555
4   430.0    29.0      34.0  12.4440  5.1340

In [128]:
y=fish['Species']
y.value_counts()

Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: Species, dtype: int64

In [122]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

In [123]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train, y_train)

pred_svm = clf_svm.predict(X_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))


--- SVM Classifier ---
0.425
[[ 7  0  1  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 3  0 10  0  0  0  0]
 [ 1  0  6  0  0  0  0]
 [ 1  0  4  0  0  0  0]
 [ 0  0  1  0  0  0  0]
 [ 1  0  2  0  0  0  0]]


In [124]:
# Build a logistic regression classifier and predict

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.775
[[ 8  0  0  0  0  0  0]
 [ 0  1  0  0  2  0  0]
 [ 0  0 13  0  0  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  3  0  1  1  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  3  0  0  0  0]]


In [125]:
clf_nn = MLPClassifier(random_state=0)
clf_nn.fit(X_train, y_train)

pred_nn = clf_nn.predict(X_test)

print ("\n--- Neural Network Classifier ---")
print (accuracy_score(y_test, pred_nn))
print (confusion_matrix(y_test, pred_nn))


--- Neural Network Classifier ---
0.55
[[ 8  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0]
 [ 1  0 12  0  0  0  0]
 [ 0  0  6  1  0  0  0]
 [ 0  0  3  1  0  1  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  3  0  0  0  0]]


In [126]:
# Build a decision tree classifier and predict

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.7
[[ 8  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0]
 [ 0  0 10  0  3  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  2  0  1  1  1]
 [ 0  0  0  0  0  1  0]
 [ 0  0  2  0  0  0  1]]


In [127]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.7
[[ 8  0  0  0  0  0  0]
 [ 0  0  1  0  2  0  0]
 [ 0  0 10  0  3  0  0]
 [ 0  0  0  7  0  0  0]
 [ 0  0  3  0  2  0  0]
 [ 0  0  0  0  0  1  0]
 [ 0  0  3  0  0  0  0]]
